FROM java:latest
MAINTAINER Amit Borase <aborase@eng.ucsd.edu>
# RUN apt-get update && apt-get install -y python
# RUN apt-get update && apt-get install -y default-jre
COPY catserver.class /catserver.class
COPY catclient.class /catclient.class
# RUN /bin/bash
